### ISSUE TITLE
Getting The JSON property [alg] received an invalid type of [type] from API when using ibmsecurity.isam.aac.api_protection.definitions.update

### ISSUE THREAD

**Issue by kalemontes** [IBM-Security/ibmsecurity#283]
Hi,
When using the method `ibmsecurity.isam.aac.api_protection.definitions.update` am getting the following error from ISAM API : 
> HTTP Return code: 400', u'{\"result\":\"FBTRBA241E The JSON property [enc] received an invalid type of [type]. The expected type was [[string]].<br>FBTRBA241E The JSON property [alg] received an invalid type of [type]. The expected type was [[string]].\"}

This arrises when the `oidc` parameter contains `enc` object has null/None properties : 
```json
"enc": {
    "alg": null,
    "enabled": false,
    "enc": null
},
```
The issue is that when calling `ibmsecurity.isam.aac.api_protection.definitions.get` we get this structure when encryption on OIDC definition is disabled, for instance :
```
    "ansible_facts": {
        "activations": [
            "wga",
            "mga",
            "federation"
        ],
        "firmware_build": "20191223-0359",
        "firmware_label": "isam_9.0.7.1_20191223-0359",
        "model": "Appliance",
        "product_description": "IBM Security Access Manager",
        "product_name": "isam",
        "version": "9.0.7.1"
    },
    "changed": false,
    "cmd": "ibmsecurity.isam.aac.api_protection.definitions.get(isamAppliance=isam_server, force=False, name=\"oidc_app_test\")",
    "data": {
        "accessPolicyId": 3,
        "accessTokenLength": 20,
        "accessTokenLifetime": 300,
        "authorizationCodeLength": 30,
        "authorizationCodeLifetime": 300,
        "datecreated": "2019-09-03T13:24:08Z",
        "description": "Configuration OIDC utile pour permettre aux application de simuler des nouveaux attributs, durees de jetons differentes, etc.",
        "enableMultipleRefreshTokensForFaultTolerance": true,
        "enforceSingleAccessTokenPerGrant": false,
        "enforceSingleUseAuthorizationGrant": true,
        "grantTypes": [
            "IMPLICIT_GRANT",
            "AUTHORIZATION_CODE"
        ],
        "id": "25",
        "issueRefreshToken": true,
        "lastmodified": "2020-10-07T14:51:48Z",
        "mappingRules": [
            {
                "id": "76",
                "type": "PRE_TOKEN_GENERATION"
            },
            {
                "id": "77",
                "type": "POST_TOKEN_GENERATION"
            }
        ],
        "maxAuthorizationGrantLifetime": 600,
        "name": "oidc_app_test",
        "oidc": {
            "alg": "RS256",
            "attributeSources": [
                {
                    "attributeName": "full_name",
                    "attributeSourceId": "20"
                },
                {
                    "attributeName": "given_name",
                    "attributeSourceId": "6"
                },
                {
                    "attributeName": "family_name",
                    "attributeSourceId": "9"
                },
                {
                    "attributeName": "email",
                    "attributeSourceId": "27"
                },
                {
                    "attributeName": "locale",
                    "attributeSourceId": "8"
                },
                {
                    "attributeName": "role",
                    "attributeSourceId": "12"
                },
                {
                    "attributeName": "updated_at",
                    "attributeSourceId": "14"
                },
                {
                    "attributeName": "groups",
                    "attributeSourceId": "1"
                },
                {
                    "attributeName": "employee_number",
                    "attributeSourceId": "16"
                },
                {
                    "attributeName": "employee_type",
                    "attributeSourceId": "3"
                },
                {
                    "attributeName": "regate_code",
                    "attributeSourceId": "17"
                },
                {
                    "attributeName": "fonction",
                    "attributeSourceId": "19"
                },
                {
                    "attributeName": "apim_audience",
                    "attributeSourceId": "26"
                }
            ],
            "cert": "mycert",
            "db": "oauth_idp_keys",
            "dynamicClients": false,
            "enabled": true,
            "enc": {
                "alg": null,
                "enabled": false,
                "enc": null
            },
            "iss": "https://myissuer",
            "issueSecret": false,
            "lifetime": 300,
            "poc": "https://myissuer/mga"
        },
        "pinLength": 4,
        "pinPolicyEnabled": false,
        "refreshTokenLength": 40,
        "tcmBehavior": "NEVER_PROMPT",
        "tokenCharSet": "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"
    },
    "delta": "0:00:00.534219",
    "end": "2020-10-07 17:33:42.907066",
    "invocation": {
        "module_args": {
            "action": "ibmsecurity.isam.aac.api_protection.definitions.get",
            "adminProxyApplianceShortName": false,
            "adminProxyHostname": null,
            "adminProxyPort": 443,
            "adminProxyProtocol": "https",
            "appliance": "myappliance",
            "force": false,
            "isamapi": {
                "name": "oidc_app_test"
            },
            "lmi_port": 443,
            "log": "INFO",
            "omitAdminProxy": false,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
        }
    },
    "rc": 0,
    "start": "2020-10-07 17:33:42.372847",
    "status_code": 0,
    "stdout": "[2020-10-07 17:33:41,862] [PID:1604 TID:140242104743744] [INFO] [ibmsecurity.appliance.ibmappliance] [_log_desc():38] *** Retrieving version  [PID:1604 TID:140242104743744] [INFO] [urllib3.connectionpool] [_new_conn():735] Starting new HTTPS connection (1): myappliance\n[2020-10-07 17:33:42,3744] [INFO] [ibmsecurity.appliance.ibmappliance] [_log_desc():38] *** Get Setup Complete Settings ***\n[2020-10-07 17:33:42,210] [PID:1604 TID:140242104743ance.ibmappliance] [_log_desc():38] *** Retrieving activations ***\n[2020-10-07 17:33:42,373] [PID:1604 TID:140242104743744] [INFO] [ibmsecurity.appliance.i*** Retrieve a list of API protection definitions ***\n[2020-10-07 17:33:42,373] [PID:1604 TID:140242104743744] [INFO] [ibmsecurity.appliance.ibmappliance] les satisfying requirement: [u'mga', u'federation']\n[2020-10-07 17:33:42,651] [PID:1604 TID:140242104743744] [INFO] [ibmsecurity.isam.aac.api_protection.de definition oidc_app_test id: 25\n[2020-10-07 17:33:42,651] [PID:1604 TID:140242104743744] [INFO] [ibmsecurity.appliance.ibmappliance] [_log_desc():38] *** tion definition ***\n[2020-10-07 17:33:42,651] [PID:1604 TID:140242104743744] [INFO] [ibmsecurity.appliance.ibmappliance] [_process_warnings():143] Modules ', u'federation']\n",
    "stdout_lines": [
        "[2020-10-07",
        "17:33:41,862]",
        "[PID:1604",
        "TID:140242104743744]",
        "[INFO]",
        "[ibmsecurity.appliance.ibmappliance]",
        "[_log_desc():38]",
        "***",
        "Retrieving",
        "version",
        "***",
        "[2020-10-07",
        "17:33:41,871]",
        "[PID:1604",
        "TID:140242104743744]",
        "[INFO]",
        "[urllib3.connectionpool]",
        "[_new_conn():735]",
        "Starting",
        "new",
        "HTTPS",
        "connection",
        "(1):",
        "cdyv0133-exploit",
        "[2020-10-07",
        "17:33:42,054]",
        "[PID:1604",
        "TID:140242104743744]",
        "[INFO]",
        "[ibmsecurity.appliance.ibmappliance]",
        "[_log_desc():38]",
        "***",
        "Get",
        "Setup",
        "Complete",
        "Settings",
        "***",
        "[2020-10-07",
        "17:33:42,210]",
        "[PID:1604",
        "TID:140242104743744]",
        "[INFO]",
        "[ibmsecurity.appliance.ibmappliance]",
        "[_log_desc():38]",
        "***",
        "Retrieving",
        "activations",
        "***",
        "[2020-10-07",
        "17:33:42,373]",
        "[PID:1604",
        "TID:140242104743744]",
        "[INFO]",
        "[ibmsecurity.appliance.ibmappliance]",
        "[_log_desc():38]",
        "***",
        "Retrieve",
        "a",
        "list",
        "of",
        "API",
        "protection",
        "definitions",
        "***",
        "[2020-10-07",
        "17:33:42,373]",
        "[PID:1604",
        "TID:140242104743744]",
        "[INFO]",
        "[ibmsecurity.appliance.ibmappliance]",
        "[_process_warnings():143]",
        "Modules",
        "satisfying",
        "requirement:",
        "[u'mga',",
        "u'federation']",
        "[2020-10-07",
        "17:33:42,651]",
        "[PID:1604",
        "TID:140242104743744]",
        "[INFO]",
        "[ibmsecurity.isam.aac.api_protection.definitions]",
        "[search():59]",
        "Found",
        "definition",
        "oidc_app_test",
        "id:",
        "25",
        "[2020-10-07",
        "17:33:42,651]",
        "[PID:1604",
        "TID:140242104743744]",
        "[INFO]",
        "[ibmsecurity.appliance.ibmappliance]",
        "[_log_desc():38]",
        "***",
        "Retrieve",
        "a",
        "specific",
        "API",
        "protection",
        "definition",
        "***",
        "[2020-10-07",
        "17:33:42,651]",
        "[PID:1604",
        "TID:140242104743744]",
        "[INFO]",
        "[ibmsecurity.appliance.ibmappliance]",
        "[_process_warnings():143]",
        "Modules",
        "satisfying",
        "requirement:",
        "[u'mga',",
        "u'federation']"
    ]
}
```

I was hoping to be able to update some properties of the Definition by getting the current Definition object, and modifying just the properties i need to update. Am using this ansible role if it helps to reproduce : 

```yaml
---
- name: "Get OAuth 2.0 Definition '{{update_oauth_definition_name}}'"
  isam:
    appliance: "{{ inventory_hostname }}"
    adminProxyProtocol: "{{ adminProxyProtocol | default(omit) }}"
    adminProxyHostname: "{{ adminProxyHostname | default(omit) }}"
    adminProxyPort: "{{ adminProxyPort | default(omit) }}"
    adminProxyApplianceShortName: "{{ adminProxyApplianceShortName | default(omit) }}"
    omitAdminProxy: "{{ omitAdminProxy | default(omit) }}"
    username: "{{ username }}"
    password: "{{ password }}"
    lmi_port: "{{ port | default(omit) }}"
    log: "{{ log_level | default(omit) }}"
    force: "{{ force | default(omit) }}"
    action: ibmsecurity.isam.aac.api_protection.definitions.get
    isamapi:
      name: "{{update_oauth_definition_name}}"
  register: "oauth_def_before_update"

- debug:
    var: "oauth_def_before_update"

- name: "Build isamapi request object for OAuth 2.0 Definition"
  set_fact:
    isamapi_request_obj: "{{ oauth_def_before_update.data
      | combine({update_oauth_definition_param:update_oauth_definition_value}, recursive=True) }}"

- name: "Clean isam request object for OAuth 2.0 Definition"
  set_fact:
    isamapi_request_clean_obj: "{{ isamapi_request_clean_obj | default({}) | combine({item.key: item.value}) }}"
  when: "{{item.key not in ['id', 'datecreated', 'lastmodified', 'mappingRules']}}"
  with_dict: "{{isamapi_request_obj}}"

- debug:
    var: "isamapi_request_clean_obj"

- name: "Update OAuth 2.0 Definition '{{update_oauth_definition_name}}' parameter '{{update_oauth_definition_param}}'"
  isam:
    appliance: "{{ inventory_hostname }}"
    adminProxyProtocol: "{{ adminProxyProtocol | default(omit) }}"
    adminProxyHostname: "{{ adminProxyHostname | default(omit) }}"
    adminProxyPort: "{{ adminProxyPort | default(omit) }}"
    adminProxyApplianceShortName: "{{ adminProxyApplianceShortName | default(omit) }}"
    omitAdminProxy: "{{ omitAdminProxy | default(omit) }}"
    username: "{{ username }}"
    password: "{{ password }}"
    lmi_port: "{{ port | default(omit) }}"
    log: "{{ log_level | default(omit) }}"
    force: "{{ force | default(omit) }}"
    action: ibmsecurity.isam.aac.api_protection.definitions.update
    isamapi: "{{isamapi_request_clean_obj}}"
  notify:
      - Commit Changes

```

**Comment by ram-ibm** [comment]
I highly recommend using set() function - that will make your life simpler. I have passed the following for "enc":
```
        enc:
          alg: "null"
          enabled: False
          enc: "null"
```

You may want to use get() for the mapping rules - so you can find the actual id values.
