### ISSUE TITLE
Idempotency issue with set_junction (1 of 2)

### ISSUE THREAD

**Issue by LouBea** [IBM-Security/ibmsecurity#63]
Hi,

I am calling the set_junction role and the idempotency does not work, the jct is always identified as changed.

The call to the role is like this:

```
- name: Set the junctions from original IBM role
  hosts: rp
  roles:
    - role: set_junction
      set_junction_junction_point: "/abc"
      set_junction_junction_type: "ssl"
      set_junction_reverseproxy_id: "default"
      set_junction_server_hostname: "intg-abc.def.gh.inet"
      set_junction_server_port: 464
      set_junction_scripting_support: "yes"
      set_junction_remote_http_header: "['iv_groups', 'iv_user']"
      # set_junction_junction_cookie_javascript_block: "onfocus trailer"
      set_junction_junction_cookie_javascript_block: "trailer,onfocus"
      set_junction_virtual_hostname: "intg-abc.def.gh.inet:464"
      ignore_errors: no
```

There are actually 2 different issues preventing the idempotency of the call, I will log them in separate issue, this is 1 of 2

For the param set_junction_junction_cookie_javascript_block I am passing "trailer,onfocus"
but in junctions.py in the "set" method the "get" call to obtain the json of the existing jct return this param as "onfocus trailer"

So when comparing the new jct being requested (jct_json) & the existing one (exist_jct) , this parameter makes the 2 json always different.

I tried setting set_junction_junction_cookie_javascript_block with value  "onfocus trailer" but I get an error when doing this.

Thanks for your help,
Louis
