### ISSUE TITLE
Idempotency issue with set_junction (2 of 2)

### ISSUE THREAD

**Issue by LouBea** [IBM-Security/ibmsecurity#64]
Hi,

I am calling the set_junction role and the idempotency does not work, the jct is always identified as changed.

The call to the role is like this:

```
- name: Set the junctions from original IBM role
  hosts: rp
  roles:
    - role: set_junction
      set_junction_junction_point: "/abc"
      set_junction_junction_type: "ssl"
      set_junction_reverseproxy_id: "default"
      set_junction_server_hostname: "intg-abc.def.gh.inet"
      set_junction_server_port: 464
      set_junction_scripting_support: "yes"
      set_junction_remote_http_header: "['iv_groups', 'iv_user']"
      # set_junction_junction_cookie_javascript_block: "onfocus trailer"
      set_junction_junction_cookie_javascript_block: "trailer,onfocus"
      set_junction_virtual_hostname: "intg-abc.def.gh.inet:464"
      ignore_errors: no
```

There are actually 2 different issues preventing the idempotency of the call, I will log them in separate issue, this is 2 of 2

There are 3 (new) parameters that are passed to the "set" method of junctions.py 'http2_junction', 'http2_proxy' & 'sni_name'.

When comparing the 2 json to check for idempotency, these 3 params are included in the new jct json (jct_json) but they are not in the old json  (exist_jct) so the 2 json are always found to be different.

Thanks for your help,
Louis
